### ISSUE TITLE
no such file or directory: 'data/features/medvidqa/feature_shapes.json'

### ISSUE THREAD

**Issue by ghost** [deepaknlp/MedVidQACL#2]
hi, i have downloaded the VideoFeatures Files , but there is no such file named “feautre_shapes.json”.  where can i got it ?

**Comment by deepaknlp** [comment]
Hi @EZodiac,

 The “feautre_shapes.json” is available under the ``MedVidQA/I3D`` subdirectory of the ``VideoFeatures`` directory.

**Comment by ghost** [comment]
thx, i have found it. It was named "feature_shape.json", missing an "s" suffix.
