### ISSUE TITLE
video_feature KeyError

### ISSUE THREAD

**Issue by mohammedmahdiali** [deepaknlp/MedVidQACL#5]
video_feature = self.video_features[record['vid']]
KeyError: 'jVnpRX2Rywo'

**Comment by deepaknlp** [comment]
Did you download the video features from here : https://bionlp.nlm.nih.gov/VideoFeatures.zip
?

**Comment by mohammedmahdiali** [comment]
yes i solve it by add the feature path. not only the video id

video_feature = self.video_features[f"path/to/feature_dir/{record['vid']}"]

Thank you
